packages:
  profile: !include ../packages/profiles/stock-minimal.yaml
  target:  !include ../packages/targets/stock-srf10-4m-target.yaml

kauf_deprecations:
  yaml_file: "__KAUF_RGBS_LEGACY_YAML_4M_MIN__"

external_components:
  - source:
      type: git
      url: https://github.com/KaufHA/common
    components: [kauf_deprecations]
