# Default 4MiB ESP8266 entrypoint (kauf profile + 4m target).
substitutions:
  components: kauf
  profile:    default

packages:
  Kauf.Profile: !include profiles/${components}-${profile}.yaml
  Kauf.Target:  !include targets/${components}-srf10-4m-target.yaml
