# Default 1MiB ESP8266 entrypoint (kauf profile + 1m target).
substitutions:
  components: kauf
  profile:    default

packages:
  Kauf.Profile: !include profiles/${components}-${profile}.yaml
  Kauf.Target:  !include targets/${components}-srf10-1m-target.yaml
